services:
  - type: web
    name: imo-creator-backend
    plan: free
    branch: master
    region: oregon
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: COMPOSIO_API_KEY
        value: ak_t-F0AbvfZHUZSUrqAGNn
      - key: MCP_API_URL
        value: https://backend.composio.dev
      - key: PORT
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DOCTRINE_DB
        value: shq
      - key: DOCTRINE_SUBHIVE
        value: "03"
      - key: DOCTRINE_APP
        value: imo
      - key: DOCTRINE_VER
        value: "1"
      - key: ALLOW_ORIGIN
        value: "https://imo-creator.vercel.app"
      - key: FRONTEND_URL
        value: "https://imo-creator.vercel.app"