console.log("[Factory] Development UI Cockpit");
console.log("=============================");
console.log("");
console.log("Available commands:");
console.log("  npm run init <app-name>     - Create new app with IMO standards");
console.log("  npm run recall <repo-path>  - Inject IMO compliance into existing repo");
console.log("  npm run env:check          - Validate environment configuration");
console.log("  npm run compliance:check   - Check repository compliance");
console.log("  npm run audit             - Run complete Garage Bay audit");
console.log("");
console.log("Factory Status: Ready");
console.log("Mechanic Status: Ready");
console.log("Garage-MCP: Integrated");
console.log("HEIR System: Available");